config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :trains do
        resources :workouts
      end
    end
  end

  resources :workouts
  resources :trains
  resources :exercises
  resources :train_plans
  resources :exercise_types
  resources :train_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1 or /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy!

    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:train_plan_id, :approach_number, :repeats, :mass)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <p>
    <strong>Train plan:</strong>
    <%= exercise.train_plan_id %>
  </p>

  <p>
    <strong>Approach number:</strong>
    <%= exercise.approach_number %>
  </p>

  <p>
    <strong>Repeats:</strong>
    <%= exercise.repeats %>
  </p>

  <p>
    <strong>Mass:</strong>
    <%= exercise.mass %>
  </p>

</div>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :train_plan_id, style: "display: block" %>
    <%= form.text_field :train_plan_id %>
  </div>

  <div>
    <%= form.label :approach_number, style: "display: block" %>
    <%= form.number_field :approach_number %>
  </div>

  <div>
    <%= form.label :repeats, style: "display: block" %>
    <%= form.number_field :repeats %>
  </div>

  <div>
    <%= form.label :mass, style: "display: block" %>
    <%= form.number_field :mass %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Show this exercise", @exercise %> |
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exercises</h1>

<div id="exercises">
  <% @exercises.each do |exercise| %>
    <%= render exercise %>
    <p>
      <%= link_to "Show this exercise", exercise %>
    </p>
  <% end %>
</div>

<%= link_to "New exercise", new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercise %>

<div>
  <%= link_to "Edit this exercise", edit_exercise_path(@exercise) %> |
  <%= link_to "Back to exercises", exercises_path %>

  <%= button_to "Destroy this exercise", @exercise, method: :delete %>
</div>